name: test

on:
  workflow_run:
    workflows: ["trigger"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: test/echo
        run: echo triggered
